export const SYNC_ACTION = 'SYNC_ACTION'

export const ASYNC_ACTION_REQUEST = 'ASYNC_ACTION_REQUEST'
export const ASYNC_ACTION_SUCCESS = 'ASYNC_ACTION_SUCCESS'
export const ASYNC_ACTION_ERROR = 'ASYNC_ACTION_ERROR'
