export const MOST_N_RECENT_MOVIES_REQUEST = 'MOST_N_RECENT_MOVIES_REQUEST'
export const MOST_N_RECENT_MOVIES_SUCCESS = 'MOST_N_RECENT_MOVIES_SUCCESS'
export const MOST_N_RECENT_MOVIES_FAILURE = 'MOST_N_RECENT_MOVIES_FAILURE'

export const MOVIES_FOR_GENRE_REQUEST = 'MOVIES_FOR_GENRE_REQUEST'
export const MOVIES_FOR_GENRE_SUCCESS = 'MOVIES_FOR_GENRE_SUCCESS'
export const MOVIES_FOR_GENRE_FAILURE = 'MOVIES_FOR_GENRE_FAILURE'

export const CREATE_MOVIE_REQUEST = 'CREATE_MOVIE_REQUEST'
export const CREATE_MOVIE_SUCCESS = 'CREATE_MOVIE_SUCCESS'
export const CREATE_MOVIE_FAILURE = 'CREATE_MOVIE_FAILURE'

export const DELETE_MOVIE_REQUEST = 'DELETE_MOVIE_REQUEST'
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS'
export const DELETE_MOVIE_FAILURE = 'DELETE_MOVIE_FAILURE'
