export const MOST_N_RECENT_MOVIES_REQUEST = 'MOST_N_RECENT_MOVIES_REQUEST'
export const MOST_N_RECENT_MOVIES_SUCCESS = 'MOST_N_RECENT_MOVIES_SUCCESS'
export const MOST_N_RECENT_MOVIES_FAILURE = 'MOST_N_RECENT_MOVIES_FAILURE'
